version: "3.9"
services:
  tunnel:
    container_name: cloudflared-tunnel
    image: cloudflare/cloudflared
    restart: unless-stopped
    command: tunnel run
    environment:
      TUNNEL_TOKEN: ${CLOUDFLARED_TOKEN}
  cms:
    image: sakharovde/sakharov.de-cms:v0.0.4
    platform: linux/amd64
    environment:
      DATABASE_CLIENT: ${CMS_DATABASE_CLIENT}
      DATABASE_HOST: ${CMS_DATABASE_HOST}
      DATABASE_PORT: ${CMS_DATABASE_PORT}
      DATABASE_NAME: ${CMS_DATABASE_NAME}
      DATABASE_USERNAME: ${CMS_DATABASE_USERNAME}
      DATABASE_PASSWORD: ${CMS_DATABASE_PASSWORD}
      NODE_ENV: ${CMS_NODE_ENV}
      HOST: ${CMS_HOST}
      PORT: ${CMS_PORT}
      APP_KEYS: ${CMS_APP_KEYS}
      API_TOKEN_SALT: ${CMS_API_TOKEN_SALT}
      ADMIN_JWT_SECRET: ${CMS_ADMIN_JWT_SECRET}
      JWT_SECRET: ${CMS_JWT_SECRET}
      S3_CDN_DOMAIN: ${CMS_S3_CDN_DOMAIN}
      S3_ACCESS_KEY_ID: ${CMS_S3_ACCESS_KEY_ID}
      S3_SECRET_ACCESS_KEY: ${CMS_S3_SECRET_ACCESS_KEY}
      S3_ENDPOINT: ${CMS_S3_ENDPOINT}
      S3_BUCKET: ${CMS_S3_BUCKET}
  database:
    image: postgres:15
    restart: always
    volumes:
      - /private/var/lib/postgresql/data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGDATA: /var/lib/postgresql/data/pgdata
